# Example

aws_access_token: qweasdzxc
service:
  - mongo_db:
      password: 12345
      port: 123456
      schema: users
    postgres:
      password: 67890
      port: 678901
      schema: passwords